In [1]:
import sqlite3
import pandas as pd
import numpy as np
from pathlib import Path
import json

In [2]:
# Connect to the database
conn = sqlite3.connect('database_sozluk/v12/v12.gts.sqlite3.db')

# Get all the table names
cursor = conn.cursor()
cursor.execute("SELECT name from sqlite_master WHERE type='table';")
tables = cursor.fetchall()

In [3]:
# Read all tables into a dictionary of DataFrames#
dfs = {}
for table_name in tables:
    table = table_name[0]
    print(f"- Reading table: {table}")
    dfs[table] = pd.read_sql_query(f"SELECT * FROM {table}", conn)
    print(f"    ✔ Rows: {len(dfs[table])}, Columns: {len(dfs[table].columns)}")
conn.close()

- Reading table: ornek
    ✔ Rows: 45392, Columns: 7
- Reading table: anlam
    ✔ Rows: 133037, Columns: 7
- Reading table: anlam_ozellik
    ✔ Rows: 122032, Columns: 2
- Reading table: atasozu
    ✔ Rows: 16666, Columns: 3
- Reading table: madde
    ✔ Rows: 99236, Columns: 20
- Reading table: ozellik
    ✔ Rows: 67, Columns: 5
- Reading table: yazar
    ✔ Rows: 3470, Columns: 4
- Reading table: madde_atasozu
    ✔ Rows: 417030, Columns: 2

In [4]:
dfs['ornek'][:10]

,ornek_id,anlam_id,kac,ornek_sira,ornek,yazar_id,yazar_vd
0,3,23844,1,1,Benim işim yok senin o dilli kardeşlerinin ara...,57.0,
1,5,23848,1,1,O subayları esir alıp askere getiren kumandan ...,28.0,
2,6,23851,1,1,Şimdi bu elemanları ince ince dileceğim.,76.0,
3,12,23883,1,1,"Pencerenin önünde, sırtı odaya dönük olarak di...",7.0,
4,13,23884,1,1,Onun nasıl hiç sarsılmadan dimdik durduğunu gö...,13.0,
5,15,23890,1,1,Yazık ki bu sanat ve din bahsinde bana arkadaş...,15.0,
6,16,23895,1,1,Senin yanına fedai yazılacağım ve dini bir uğr...,15.0,
7,17,23896,1,1,Ufacık bir düşüncenin en büyük bir dikkati ifl...,23.0,
8,18,23898,1,1,"Şevki Bey dedi, dinin aşkına sen Romenlerin ge...",10.0,
9,19,23903,1,1,Din adamları halk üzerinde büyük bir telkin ku...,175.0,

In [5]:
dfs['anlam'][:10]

,anlam_id,anlam_sira,anlam,fiil,gos,madde_id,tipkes
0,0,1,"Bir topluluk karşısında etkili, açık, düzgün k...",0,0,28579,0
1,1,1,Acınılmak işi,0,0,6142,0
2,2,1,Tuhaf kimse,0,0,6143,0
3,3,2,"Tuhaf, alışılmadık, garip şey",0,0,6143,0
4,4,1,Açık fikirli olma durumu; açık görüşlülük,0,0,6144,0
5,5,2,► nişanlanma,0,0,6145,0
6,6,1,Adaletli olma durumu,0,0,6146,0
7,7,1,► sayma,0,0,6147,0
8,8,1,► sayılma,0,0,6148,0
9,9,1,Adliye içerisinde güvenliği sağlayıp cumhuriye...,0,0,6149,0

In [6]:
dfs['anlam_ozellik'][:10]

   anlam_id  ozellik_id
0     25840          19
1     25840          41
2     25841          19
3     25841          33
4     25842          32
5     25844          19
6     25845          22
7     25846          19
8     25847          23
9     25848          20

In [7]:
dfs['atasozu'][:10]

   madde_id                     madde on_taki
0         3              dulda tutmak    None
1        15               duman almak    None
2        16          duman altı etmek    None
3        17          duman altı olmak    None
4        18            duman attırmak    None
5        19               duman etmek    None
6        20               duman olmak    None
7        21              duman vermek    None
8        22       dumanı doğru çıksın    None
9        23  dumanı tepesinden çıkmak    None

In [8]:
dfs['madde'][:10]

,madde_id,anlam_gor,anlam_say,birlesikler,cesit_say,cesit,cogul_mu,egik_mi,font,gosterim_tarihi,kac,kelime_no,lisan_kodu,lisan,madde_duz,madde,on_taki,ozel_mi,taki,telaffuz
0,1,0,1,None,0,0,0,0,None,None,0,14800,0,,dulavrat otu,dulavrat otu,None,0,None,None
1,2,0,2,None,1,0,0,0,None,None,0,14801,0,,dulda,dulda,None,0,None,None
2,3,0,1,None,0,1,0,0,None,2023-11-07,0,14801,0,,dulda tutmak,dulda tutmak,None,0,None,None
3,4,0,1,None,0,0,0,0,None,None,0,14802,0,,duldalama,duldalama,None,0,None,None
4,5,0,1,None,0,0,0,0,None,None,0,14803,0,,duldalamak,duldalamak,None,0,None,None
5,6,0,1,None,0,0,0,0,None,None,0,14804,0,,duldalanma,duldalanma,None,0,None,None
6,7,0,1,None,0,0,0,0,None,None,0,14805,0,,duldalanmak,duldalanmak,None,0,None,None
7,8,0,1,None,0,0,0,0,None,None,0,14806,0,,duldali,duldalı,None,0,None,None
8,9,0,1,None,0,0,0,0,None,None,0,14807,0,,duldasiz,duldasız,None,0,None,None
9,10,0,1,None,0,0,0,0,None,None,0,14808,0,,dulluk,dulluk,None,0,ğu,None

In [9]:
dfs['ozellik'][:20]

    ozellik_id  ekno kisa_adi              tam_adi  tur
0           18    29     ünl.                ünlem    3
1           19    30       a.                 isim    3
2           20    31      sf.                sıfat    3
3           21    32       -e                   -e    3
4           22    33       -i                   -i    3
5           23    34     nsz.             nesnesiz    3
6           24    35      zf.                 zarf    3
7           25    36      -le                  -le    3
8           26    37     -den                 -den    3
9           27    38       e.                 edat    3
10          28    39     bağ.               bağlaç    3
11          29    40      zm.                zamir    3
12          30    41     argo                 argo    4
13          31    42     esk.              eskimiş    4
14          32    43     mec.                mecaz    4
15          33    44     ağz.           ağızlardan    4
16          34    45     tkz.  teklifsiz konuşmada    4
17          35    46     alay           alay yollu    4
18          36    47     kaba       kaba konuşmada    4
19          37    48     şaka           şaka yollu    4

In [10]:
dfs['yazar'][:10]

   yazar_id  ekno          kisa_adi                tam_adi
0         1     8  S. F. Abasıyanık   Sait Faik Abasıyanık
1         2   127          H. Taner           Haldun Taner
2         3   128           Atasözü                Atasözü
3         4   129        F. R. Atay       Falih Rıfkı Atay
4         5   130       Karacaoğlan            Karacaoğlan
5         6   131    E. B. Koryürek    Enis Behiç Koryürek
6         7   132          T. Buğra            Tarık Buğra
7         8   133    R. N. Güntekin    Reşat Nuri Güntekin
8         9   134         M. Yesari          Mahmut Yesari
9        10   135     M. Ş. Esendal  Memduh Şevket Esendal

In [ ]:
dfs['madde_atasozu'][:10]

In [ ]:
def xind(indices):
    '''This function enhances pandas isin method'''
    if isinstance(indices, int) or isinstance(indices, np.int64):
        return [indices]
    elif isinstance(indices, list) or isinstance(indices, np.ndarray):
        return indices
    else:
        raise TypeError("Expected indices to be an int or a list.")

In [ ]:
'''
Creation of the structure using the tables

Structure:
----------
Madde (Entry/Word)
├── Anlam (Meaning)
│   ├── [Özellik 1, Özellik 2] Anlam 1
│   │   └── Örnek 1 - Yazar 1
│   └── [Özellik 3] Anlam 2
│       └── Örnek 2 - Yazar 2
└── Madde atasözü (if exists)

Components:
-----------
- Madde: Main dictionary entry/word
- Anlam: Meaning/definition (can have multiple)
- Özellikler: Properties/attributes for each meaning
- Örnek: Example sentence/usage
- Yazar: Author/source of the example
- Madde öntakı: Related prefix entry for a proverb (optional)
'''

# Initialization
sozluk = {}

In [ ]:
# Processing loop
for i in range(len(dfs['madde'])):

    # 0. Extract basic madde information
    madde = dfs['madde'].iloc[i]
    madde_id = madde['madde_id'].item() # np.int64
    madde_name = madde['madde']
    madde_birlesikler = madde['birlesikler']
    
    # 1. More detailed information
    # 1.1 Fetch the language
    madde_lisan = madde['lisan'] if madde['lisan'] != '' else 'Türkçe'

    # 1.2. Fetch the on_taki field for the proverb madde (if exists)
    is_atasozu_or_deyim =  madde_id in dfs['atasozu']['madde_id'].tolist()
    
    if is_atasozu_or_deyim:
        on_taki = dfs['atasozu'].loc[dfs['atasozu']['on_taki'] == madde_id, 'on_taki'] + ' '
    else:
        on_taki = ''
    madde_name_ext = on_taki + madde_name

    # 1.2. Fetch the anlam and ozellik fields for the entry
    madde_anlam = dfs['anlam'].loc[dfs['anlam']['madde_id'] == madde_id, 'anlam'].tolist()
    madde_anlam_id = dfs['anlam'].loc[dfs['anlam']['madde_id'] == madde_id, 'anlam_id'].tolist()
    madde_num_anlam = len(madde_anlam)
    
    # 2.1 Fetch the ozellik ornek, and yazar associated with each anlam
    anlam_dict = {}
    for j, anlam in enumerate(madde_anlam):
        # 2.2 Fetch anlam_ozellik
        # Flow: anlam -> anlam_id -> anlam_ozellik_id -> anlam_ozellik
        anlam_id = madde_anlam_id[j]
        anlam_ozellik_id = dfs['anlam_ozellik'].loc[dfs['anlam_ozellik']['anlam_id'].isin(xind(anlam_id)), 'ozellik_id'].tolist()
        anlam_ozellik = ', '.join(dfs['ozellik'].loc[dfs['ozellik']['ozellik_id'].isin(xind(anlam_ozellik_id)), 'tam_adi'].tolist())

        # 2.3 ornek and yazar fields for the given anlam
        # anlam_ornek -> anlam_ornek_yazar_id -> anlam_ornek_yazar
        anlam_ornek = [orn for orn in dfs['ornek'].loc[dfs['ornek']['anlam_id'].isin(xind(anlam_id)), 'ornek'].tolist() if orn]
        anlam_ornek_yazar_id = [int(yid) for yid in dfs['ornek'].loc[dfs['ornek']['anlam_id'].isin(xind(anlam_id)), 'yazar_id'].fillna('').tolist() if yid]
        anlam_ornek_yazar = [yaz for yaz in dfs['yazar'].loc[dfs['yazar']['yazar_id'].isin(xind(anlam_ornek_yazar_id)), 'tam_adi'].tolist() if yaz]
        
        # 2.4 Save the anlam-ozellik-ornek-yazar data
        anlam_dict[f"{madde_id}_{anlam_id}"] = (anlam, anlam_ozellik, anlam_ornek, anlam_ornek_yazar)
        
    # Save the dictionary item
    sozluk[f"{madde_name}_{madde_id}"] = {
        "madde_id": madde_id,
        "madde_lisan": madde_lisan,
        "madde_name": madde_name,
        "madde_name_extended": madde_name_ext,
        "is_atasozu_or_deyim": is_atasozu_or_deyim,
        "on_taki": on_taki,
        "madde_birlesikler": madde_birlesikler,
        "madde_num_anlam": madde_num_anlam,
        "anlam": anlam_dict        
    }

    # Status update
    print(f"    ({i/len(dfs['madde']):.2f}%) [{madde_name}] has been processed...")

In [ ]:
# Write in a JSON file
out_file = "gts_sqlite_processed"
with open(Path("processed", out_file, '.json'), "w", encoding="utf-8") as f:
    json.dump(d, f, ensure_ascii=False, indent=2)